build:
  stage: build
  image: docker
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    SOURCE_BRANCH: $CI_COMMIT_REF_NAME
    SOURCE_COMMIT: $CI_COMMIT_SHA
    COMMIT_MSG: $CI_COMMIT_MSG
    DOCKER_REPO: $CI_PROJECT_NAME
    DOCKERFILE_PATH: hooks/
    DOCKER_TAG: $CI_COMMIT_BRANCH
    IMAGE_NAME: $DOCKER_REPO/$DOCKER_TAG
    DEST_HUB: $CI_REGISTRY

  script:
    - sh hooks/post_checkout
    - sh hooks/pre_build
    - sh hooks/build
    - sh hooks/post_build
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - sh hooks/push

  only:
    refs:
      - dev
