# Slow but savest updates
deploy_production:
  stage: deploy
  image: docker
  script:
     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
     - echo "Placeholder"
  rules:
  - if: $CI_DEPLOY_FREEZE == null
  only:
    refs:
      - production

# Adding a patch
deploy_patch:
  stage: deploy
  image: docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "Placeholder"
  rules:
  - if: $CI_DEPLOY_FREEZE == null
  only:
    refs:
      - master

# Deploying latest working development
deploy_dev:
  stage: deploy
  image: docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "Placeholder"
  only:
    refs:
      - dev
