trigger:
  stage: trigger
  script:
    - echo "Placeholder"
    #- curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master $GITLAB_BASE_URL/api/v4/projects/$APP_PROJECT_ID/trigger/pipeline
  only:
    - master
