#!/bin/sh

# https://github.com/ichbestimmtnicht/docker-autobuild-release
# Template created 2020 by Ludwig Werner Döhnert
# This work is licensed under the Creative Commons Attribution 4.0 International License.
# To view a copy of this license, visit http://creativecommons.org/licenses/by/4.0/.

. ./hooks/env.sh

# Cycle through the arches

for SR_DEST_BUILD_ARCH in ${DEST_ARCHES}
do
    sh "${SR_DEST_BUILD_ARCH}.build.sh"
    rm -f "${SR_DEST_BUILD_ARCH}.build.sh"
done

exit 0
